### ISSUE TITLE
Hacs logo appears in the background

### ISSUE THREAD

**Issue by victorvlm** [hacs/integration#1273]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.3
| Home Assistant version     | 0.110.3
| Installation method for HA | Raspberry pi docker
| Web browser                | Chrome
| Web browser version        | 81.0.4044.138

## Checklist

- [X] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Since the last update from home assistant and Hacs I see the Hacs logo in the background of almost every page. It makes scrolling annoying.

### Steps to reproduce

My steps were: 
1. Update HA
1. Update HACS
1. Install any custom card

### Screenshots

[Screenshot](https://i.imgur.com/WYNSUec.png)
## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Can't seem to find anything wrong in the logs.

```

</details>

**Comment by ludeeus** [comment]
Clear your cache, that icon file has not existed since 0.24.5

**Comment by nemec** [comment]
I'm having the exact same issue. Cleaning my browser cache does not help, nor does trying hass in a private browsing session. Is there another cache I need to clear?
I just upgraded from hass version 0.108.9 and an older version of hacs (not sure on the exact version, but I think it was last updated in April), where I did not see the issue.

|Description|Value|
|-----|-----|
|HACS version|1.0.3|
|Home Assistant version|0.110.4|
|Installation method for HA|Python virtualenv
|Web browser|Firefox (Ubuntu)|
|Web browser version|76.0.1 (64-bit)|

**Comment by nemec** [comment]
Ok, I finally fixed it. I have no idea why the private browsing session had the same issue, but after I went into Firefox's debug tools and deleted everything in the Storage tab, it was fixed once I logged in again.

You can right click -> Delete the tree entries I've boxed in red below

![2020-06-05_16-06](https://user-images.githubusercontent.com/136378/83922975-f220b300-a746-11ea-9937-dcf2267e595f.png)

**Comment by ebendl** [comment]
Having the same problem in Chromium Edge on Mac. Clearing the application storage does not get rid of it, although it does work in InPrivate mode.

**Comment by ntcong** [comment]
Clear cache and data for the site will not fix it. Only clearing cache for Chrome does.

Or you can open the file 'https://homeassistant.url/hacsfiles/iconset.js' and press Ctrl+F5

**Comment by theCheek** [comment]
> Clear cache and data for the site will not fix it. Only clearing cache for Chrome does.
> 
> Or you can open the file 'https://homeassistant.url/hacsfiles/iconset.js' and press Ctrl+F5

This worked for me. Many thanks.

**Comment by Abragus** [comment]
Still having the same problem. Cache cleared completely. Used and refreshed @ntcong's link. Same problem in Chrome, Edge, and Firefox, even when using InPrivate mode. Not sure what to do.

**Comment by Joshfindit** [comment]
Confirmed: doing “reset cache” in the app setting for the iOS app (iPad) worked to remove the background icon.

**Comment by atcapollo** [comment]
![image](https://user-images.githubusercontent.com/6827078/95267247-b3058a00-082c-11eb-8ac4-b9e8592c21ec.png)
 
Same issue here on python3.8.0 hass 115.6 and chrome. 
Clearing chrome cache storage and shift F5 doesn't work

**Comment by Adminiuga** [comment]
https://github.com/hacs/integration/issues/1273#issuecomment-650896930 worked for me

I've tried deleting most data under in dev tools under storage and for a brief moment it fixed the issue, but then it came back. The above fixed it

**Comment by Joshfindit** [comment]
Would it be worth HACS devs tossing in a cache buster on that file? Like `https://homeassistant.url/hacsfiles/iconset.js?version=20201023` or something?

**Comment by Fettkeewl** [comment]
Hello..

How do I get rid of this when its not an image?... 
i went from HACS 0.6~~ to 1.8.. Restarted HA, Cleared cache and still its here..

![image](https://user-images.githubusercontent.com/25577040/102004128-3a301c00-3d0e-11eb-9539-8a6766278873.png)

**Comment by Abragus** [comment]
I'd reinstall HACS.

**Comment by Adminiuga** [comment]
Reinstalling won't help. But why you haven't tried https://github.com/hacs/integration/issues/1273#issuecomment-650896930 ???
