### ISSUE TITLE
Unexpected frontend version

### ISSUE THREAD

**Issue by MYLE-01** [hacs/integration#1886]
![image](https://user-images.githubusercontent.com/4362345/107320162-0eaa9180-6b05-11eb-81e4-828884d2470f.png)

Did the CRTL+R

can't install or reinstall

**Comment by rbouma** [comment]
Same problem: Home Assistant 2021.2.2
Frontend version: 20210127.7 - latest

Just updated to newest version of home-assistant OS and hacs broke

**Comment by ludeeus** [comment]
Cache (from browser or proxy) is the only thing that will cause that message to appear, there is nothing that can be done to prevent that from HACS (other than removing the message but that will just hide the problem)

**Comment by rbouma** [comment]
I have tested in multiple browser + incognito windows happens after the update of hacs and the update of home assistant hypervisor and ha os, after that i cleared all the browser cache + local databases services workers etc, so everything is clean.

Then message still there and i cant open the integrations and frontend repositories tab in hacs > 
![image](https://user-images.githubusercontent.com/14012592/107351916-7f34bc80-6acb-11eb-8e32-48cc1db76397.png)

**Comment by rbouma** [comment]
so 2 people have the exact same problem after update so it looks hacs broke on this version

**Comment by rbouma** [comment]
404 on this file: hacsfiles/frontend/c.209fc72a.js

**Comment by DirkTas67** [comment]
![Screenshot_20210210_203739](https://user-images.githubusercontent.com/30079864/107562259-da57d380-6bdf-11eb-9cb5-04e6c419502e.png)

Same problem here, I'm using firefox 85.0.1 on Ubuntu Linux 20.10, cleared my cache for this page several times, restarted homeasssistant and the server.

Didn't help.

Regards

**Comment by KrunchMuffin** [comment]
Same.  Why is this closed?

**Comment by rbouma** [comment]
@KrunchMuffin @DirkTas67 @MYLE-01  I fixed this problem not because of cache but unregistered the service worker in chrome

F12 -> Application -> Service Workers -> Unregister (top right)

Then reload page

This fixed my problem.

**Comment by raman325** [comment]
I noticed this issue in the Home Assistant Mac app. To resolve there, go to preferences, click on "Refresh Frontend Cache", then "CMD + R" to hard refresh (or go to the View menu and hit reload page from there)

**Comment by willmasters** [comment]
This seems to be a problem in Firefox only, it works as expected in Chrome. It's likely a problem with HA and not with HACS.

**Comment by rbouma** [comment]
My problem in this issue was because of cloudflare cache if you have this problem en have done everthing but still have wrong frontend version and if your instance is behind cloudflare 

goto your cloudflare domein in de settings and check the tab cache you can purge everything and it works again

**Comment by frederickjh** [comment]
Thanks @rbouma! Unregistering the service worker fixed it for me too. I thought this must be a browser issue as if I opened a private browser window and logged in all was well, but clearing the browser cache did not fix it.

**Comment by frederickjh** [comment]
Maybe the message about clearing the cache should be updated to include unregistering the service workers too.

Here is a screenshot of how to do this in FireFox. On number 4 click-on the double arrows to the right to be able to select **Application**.

![image](https://user-images.githubusercontent.com/864159/116898451-addbb280-ac36-11eb-859b-285bece1f467.png)
