### ISSUE TITLE
HACS showing false available updates

### ISSUE THREAD

**Issue by satyambaba** [hacs/integration#2656]
## System Health

version | core-2022.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | aarch64
timezone | Asia/Calcutta

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.24.5
Stage | running
Available Repositories | 1103
Downloaded Repositories | 106

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 1, 2022, 5:30 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.0
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 36.0 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.0.2), SSH & Web Terminal (10.1.3), FTP (4.5.0), Frigate NVR (3.1), Mosquitto broker (6.1.1), Assistant Relay (0.7.4), Eufy Security Add-on (0.8.4), RTSP Simple Server Add-on (v0.17.6), deCONZ (6.13.0), Spotify Connect (0.11.0), Samba share (9.6.1), AppDaemon (0.8.2), Plex Media Server (2.8.0), Google Assistant SDK (2.5.0), Home Assistant Google Drive Backup (0.107.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 72
views | 15
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.0.3
-- | --
cloud_online | 26 / 53
local_online | 26 / 26

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After I upgraded to HA 2022.5, HACS is showing available updates falsely. Please look at this screenshot.

![Screenshot 2022-05-05 052025](https://user-images.githubusercontent.com/6833101/166843054-60bfb51f-e937-4eab-b032-2cf211108122.jpg)

For example - it is showing to update from v1.2.20 to v1.2.19, however v1.2.20 is the latest version which is already installed.

### Reproduction steps

1. Update to HA 2022.5

### Debug logs

```text
.
```

### Diagnostics dump

[config_entry-hacs-b9b36419bcdd41af79d6f4e4d44eb5f2.json.txt](https://github.com/hacs/integration/files/8628017/config_entry-hacs-b9b36419bcdd41af79d6f4e4d44eb5f2.json.txt)

**Comment by ludeeus** [comment]
As of now, the version offered is the latest release for these:
<https://github.com/arallsopp/hass-hue-icons/releases> (Shows 1.2.19)
<https://github.com/dummylabs/thewatchman/releases> (Shows 0.5.1)

**Comment by satyambaba** [comment]
> As of now, the version offered is the latest release for these: https://github.com/arallsopp/hass-hue-icons/releases (Shows 1.2.19) https://github.com/dummylabs/thewatchman/releases (Shows 0.5.1)

I had installed v1.2.20 and 0.5.2, and it was offered by HACS when I was on HA 2022.4.7. Please look at following links, the newer versions exist -

https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.20
https://github.com/dummylabs/thewatchman/releases/tag/v.0.5.2

**Comment by ludeeus** [comment]
Those links do not matter, they are not what is displayed as the latest version.

**Comment by satyambaba** [comment]
> Those links do not matter, they are not what is displayed as the latest version.

Thanks for your response. It seems these are integration specific bugs. 
https://github.com/arallsopp/hass-hue-icons/issues/155

**Comment by arallsopp** [comment]
Yep. I think I managed to make release 20 into a **tag** rather than a **release**. I'm pretty sure it *was* a release when I created it, but perhaps editing the notes after the event has changed how github sees it.

I've released [v.1.2.21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) and believe that fixes it.

**Comment by ludeeus** [comment]
I don't think so @arallsopp if that were the case users would not have seen 1.2.20 in the first place (and judging from the issues, some have gotten that installed.)
It's far more likely that you are hit with an issue similar to this <https://github.com/hacs/integration/issues/2556> See my comment at the bottom of that issue.
(My ticket with GitHub is still not resolved)

**Comment by arallsopp** [comment]
> I don't think so @arallsopp if that were the case users would not have seen 1.2.20 in the first place (and judging from the issues, some have gotten that installed.)

Yeah, I'm pretty sure it *was* a release, particularly as some have seen it.

> It's far more likely that you are hit with an issue similar to this #2556 See my comment at the bottom of that issue.
> (My ticket with GitHub is still not resolved)

[v.1.2.20](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.20) and 
[21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) look pretty much identical in terms of screen layout, so I'll raise a ticket with support as you suggest, and then edit  and update the release and see if that restores it.

Do you think with the edit, r20 might further confuse things by appearing after 21, or might it just keep the original commit dates?

Last point, thanks for your help, as ever! :)

**Comment by ludeeus** [comment]
You can edit 20 now, it is created before so does not matter of the order of things

**Comment by arallsopp** [comment]
Thanks Joakim. Have done that, and the release now appears. Will let you know if GH support come back with anything useful.
