### ISSUE TITLE
Changing domain not working when download custom integration

### ISSUE THREAD

**Issue by FredrikM97** [hacs/integration#4854]
## System Information

version | core-2025.10.0.dev0
-- | --
installation_type | Unsupported Third Party Container
dev | true
hassio | false
docker | true
container_arch | null
user | vscode
virtualenv | true
python_version | 3.13.7
os_name | Linux
os_version | 6.10.14-linuxkit
arch | aarch64
timezone | Europe/Stockholm
config_dir | /workspaces/HA-core/config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4924
Installed Version | 2.0.5
Stage | running
Available Repositories | 2263
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 2
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), eth0 (enabled, default, auto)
-- | --
ipv4_addresses | lo (127.0.0.1/8), eth0 (172.17.0.3/16)
ipv6_addresses | lo (::1/128), eth0 ()
announce_addresses | 172.17.0.3

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 18, 2025 at 7:53 PM
-- | --
current_recorder_run | October 5, 2025 at 5:07 PM
estimated_db_size | 27.46 MiB
database_engine | sqlite
database_version | 3.50.4

</details>

### Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/help/issues/>
- [x] This issue is related to the backend (integration part) of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This is a bug and not a feature request.
- [x] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi!

I am working on an integration and due to conflict with home assistant core I need to change the domain. However when trying to test it in hacs with a pre-release it downloads the latest stable release instead. I am trying to change from surepetcare -> surepcha

In the hacs view I see this:
<img width="454" height="96" alt="Image" src="https://github.com/user-attachments/assets/915a31da-e8e8-4ec4-9f65-6131b75788cd" />

However in the custom_components I see this:

<img width="284" height="241" alt="Image" src="https://github.com/user-attachments/assets/c3958b33-f206-4bd3-af6d-1b7d3c4dd02c" />

It is weird since the pre-release have moved the package from surepetcare -> surepcha which can be seen in the [manifest.json](https://github.com/FredrikM97/hass-surepetcare/blob/dev/custom_components/surepcha/manifest.json).

Furthermore, the release that hacs downloaded is "version": "1.4.9" and not the [pre-release](https://github.com/FredrikM97/hass-surepetcare/releases/tag/v2.0.0-dev0) as said in the UI. I cant use the service update.install:

<img width="1086" height="381" alt="Image" src="https://github.com/user-attachments/assets/c42ec598-0da0-4708-b07a-51104326f730" />

So I am stuck on the old domain and no way to test the new one out without doing a release.

This is the integration: https://github.com/FredrikM97/hass-surepetcare

Also in the view for installing I chose the pre-release but somehow it still mapping to the old domain

<img width="504" height="458" alt="Image" src="https://github.com/user-attachments/assets/6e42f4d5-8928-4d3a-8521-d3859e542ac5" />

### Reproduction steps

1. Create an integration with a release
3. Change domain and create a pre-release
4. Download the pre-release
5. Check that the pre-release did not get downloaded (check custom_components instead of UI

### Debug logs

```text
Added in the diagnostics dump
```

### Diagnostics dump

[home-assistant_2025-10-05T15-20-29.406Z.log](https://github.com/user-attachments/files/22710375/home-assistant_2025-10-05T15-20-29.406Z.log)

**Comment by FredrikM97** [comment]
After some testing I can confirm that chaning the folder from surepetcare->surepcha while in the v2.0.0-dev0 update works and now I can see the integration also have the correct version. Looks like HACS dont take a change in domain into consideration and default to latest stable and that is only truth?

**Comment by ludeeus** [comment]
Fixed by https://github.com/hacs/integration/pull/4652

FYI: in general, don't change the domain. Nothing good will
Come from it (this is the reason there is still a integration named hassio inside core).
It is way better to start over with a fresh repository.

**Comment by blair287** [comment]
> After some testing I can confirm that chaning the folder from surepetcare->surepcha while in the v2.0.0-dev0 update works and now I can see the integration also have the correct version. Looks like HACS dont take a change in domain into consideration and default to latest stable and that is only truth?

doesnt work for me

**Comment by FredrikM97** [comment]
@ludeeus thanks for quick reply! I agree, did originally not want to change the domain but I had to. Due to poor planing and small integration became bigger.

I would understand If I got an error that changing domain is not valid or when removing the integration and then install pre-release should work (no local data?). That did not be the case as it always download the latest stable release first then the pre-release? 

Found it odd that HACS reported v2.0.0-dev0 but integration reported 1.4.9 (latest release). Is it fixed in later version than 2.0.5?

Do I manually need to update HACS to test it?

**Comment by ludeeus** [comment]
Until a new release is cut, you need to apply manually, or set the "Get HACS" add-on to track dev.

**Comment by FredrikM97** [comment]
If I create a new release will that also solve it or  will the issue persist?

**Comment by ludeeus** [comment]
it can persist, but less.
Changing the domain name is not a good idea regardless if HACS is in use or not.

**Comment by FredrikM97** [comment]
I agree, thanks for the support! I will relay it to the users of the integration.
